### PR TITLE
Modularize inspector

### PR DESCRIPTION
**Pull request by skalarproduktraum**
This PR modularises the code for the inspector:
* one can define inspector groups for different node types, such that the properties for `Atmosphere` are handled via `AtmosphereProperties`, which extends `InteractiveInspectorCommand` 
* `InteractiveInspectorCommand` can have again extensions for specific UI types, this is currently available for Swing as `SwingInspectorInteractiveCommandExtension`

### CODE REVIEW

**Comment by smlpt** [comment]
I tested this and I think I found a bug: when you scroll down the inspector and change a value in any of the spinner fields, it will move to the top of the panel, requiring you to scroll down again to change the value again.

**Comment by skalarproduktraum** [comment]
@smlpt 🧲😂

I'll check that and fix it, thanks for the report 👍

**Comment by skalarproduktraum** [comment]
@smlpt This should be fixed now. Can you confirm?

**Review by kephale — CHANGES_REQUESTED** [review]
Can you please double check how this works with the Text demo? I'm getting exceptions: `Color parameter outside of expected range: Red Green`

Also, volume timeseries is good, but volumes without a time axis have an incorrect timepoint slider:
image

During this testing I also tested the atmosphere shader, and it didnt work (on `main` either, but it did work when the PR was merged :/)

**Comment by smlpt** [comment]
> @smlpt This should be fixed now. Can you confirm?
Yes, editing values works properly now.

@kephale atmosphere works on my side, both in this branch and on main. Although I also noticed that something about the blend mode or depth test must be wrong, since it is visible in front of geometrical objects (which is not the case with the AtmosphereExample in scenery), also observed by @moreApi.

I also noticed a bug in my Atmosphere input: the azimuth is supposed to go from 0 to 360° according to the properties parameter. But `setSunPositionFromTime` returns values in range -180-180°. So [line 108](https://github.com/scenerygraphics/scenery/blob/78ad6b81655ff17fde95a1b1f0d600e28e9a7798/src/main/kotlin/graphics/scenery/primitives/Atmosphere.kt#L108) should be changed to be `+ PI` instead. Should I create a branch + PR for this one line? Or do we want to fix it in this branch?

**Comment by kephale** [comment]
@smlpt i'm verifying that the atmosphere is working after a gradle clean 😊 I'd suggest doing the azimuth fix in a separate PR

Otherwise the other requested changes still seem to be needed.

**Comment by smlpt** [comment]
Atmosphere range has been fixed [in this PR](https://github.com/scenerygraphics/scenery/pull/764)

**Comment by skalarproduktraum** [comment]
@kephale Known issues should be fixed, good to go from my side 👍

**Comment by kephale** [comment]
When there is a single timepoint volume but the inspector is collapsed i get:
```
[INFO] Input field timepoint of type Integer not found, therefore it can't be removed.
[INFO] Input field playPause of type Button not found, therefore it can't be removed.
[INFO] Input field playSpeed of type Integer not found, therefore it can't be removed.
```

**Pull request merged**
