### PR TITLE
Add Atmosphere background shader to the scene

### PR DESCRIPTION
**Pull request by smlpt**
This PR adds the option to add an atmosphere background from the "Add" menu to the scene.
The atmosphere exposes three parameters in the inspector:
- `Latitude`: The current latitude of the user to display the correct sun direction based on the local time
- `Enable keybindings and manual control`: a checkbox to attach/detach keybindings. This allows the user to move the sun around with Ctrl + arrow keys and Ctrl + Shift + arrow keys for fast and slow movement respectively
- `Emission Strength`: change the brightness of the background with a default strength of 1.

This will currently require the functionality of the scenery [atmosphere-shader](https://github.com/scenerygraphics/scenery/tree/feature/atmosphere-shader) branch that has not been merged yet.

Edit: the scenery branch has changed to [this one](https://github.com/scenerygraphics/scenery/pull/707)

### CODE REVIEW

**Comment by kephale** [comment]
What scenery version should we try (jitpack or whatever)? I tried [9062d7f](https://github.com/scenerygraphics/scenery/commit/9062d7f215bd7178f6f26c57d01b399ab3ab7aed) but that [doesn't seem to build](https://jitpack.io/com/github/scenerygraphics/scenery/9062d7f/build.log) on jitpack.

**Comment by kephale** [comment]
I got this working with scenery = `c4114b0` 

The inspector UI was working, key controls, etc. It all looks good!

**Comment by smlpt** [comment]
> I got this working with scenery = `c4114b0`
> 
> The inspector UI was working, key controls, etc. It all looks good!

Glad to hear that, thanks!

**Review by kephale — APPROVED** [review]
This is super fun. I made a video that I'll post somewhere using this :D

**Pull request merged**
