### PR TITLE
UX changes, take two

### PR DESCRIPTION
**Pull request by xulman**
this is essentially #273 but:

- rebased on the recent master
- based against the most recent scenery (and ui-behaviour)
- includes the work on help menus

I've tried even to (little bit, not much time now) rearrange commits (meld fix-commits) and group them:
Screenshot_20200801_102914

### CODE REVIEW

**Comment by xulman** [comment]
PS: it is missing Kyle's better-arcball commit a4661a33202ce9f1d7a70a97253f02b48b86eac0

**Comment by skalarproduktraum** [comment]
Really nice, thank you! There's one issue though that needs fixing before we can merge: When moving to a new node (I really love the animation there!), sometimes there's a roll around the Y axis introduced. This should not happen. 

Once this is fixed, I'm happy to merge this 👍

**Comment by xulman** [comment]
> When moving to a new node (I really love the animation there!), sometimes there's a roll around the Y axis introduced.

Is this a frequent case? I mean, I can get this to see on any (my) data easily so that I could debug? Or, can you please be more specific how to reach this unwanted case?

Could it have something to do with [this](https://github.com/xulman/sciview/blob/47820e65b4347a4610ccb179a971f1b80530271d/src/main/java/sc/iview/SciView.java#L810-L815)?

**Comment by xulman** [comment]
> When moving to a new node (I really love the animation there!), sometimes there's a roll around the Y axis introduced.

Plan B: replace content of `SciView.centerOnPosition()` with BDV's transforms interpolator:
```
tpietzsch @tpietzsch čvn 22 16:23
@xulman bdv already has transform animations for transitioning between bookmarks etc
See bdv.viewer.animate.AbstractTransformAnimator and subclasses SimilarityTransformAnimator etc

tpietzsch @tpietzsch čvn 22 16:26
you will need to convert (cam_position, cam_lookForward, cam_up) to/from AffineTransform3D but that should be straightforward

tpietzsch @tpietzsch čvn 22 16:27
recognizing that, the AbstractTransformAnimator does not to any animation itself
should be maybe called Interpolator more correctly

tpietzsch @tpietzsch čvn 22 16:28
it has a get(double) method
between 0 and 1

tpietzsch @tpietzsch čvn 22 16:30
construct with SimilarityTransformAnimator( final AffineTransform3D transformStart, final AffineTransform3D transformEnd, final double cX, final double cY, final long duration )

tpietzsch @tpietzsch čvn 22 16:31
then get(0..1) --> AffineTransform3D

Vladimír Ulman @xulman čvn 22 16:32
I know I should look into the code first, but what is the purpose of the duration then? when we have get() around?

tpietzsch @tpietzsch čvn 22 16:32
but basically it just does a straight line between the "camera positions" and the shortest rotation between the orientations
The AbstractAnimator base class has

    /**
     * Sets the current time for the animation.
     * The first call starts the animation.
     *
     * @param time
     *            current time (in time units)
     */
    public void setTime( final long time ) {...}

tpietzsch @tpietzsch čvn 22 16:34
that translates millisecond time into 0..1 for the given duration in microseconds
but you don't have to use that
but maybe have a look, it does this

    /**
     * Cosine shape acceleration/ deceleration curve  of linear [0,1]
     */
    private double cos( final double t )
    {
        return 0.5 - 0.5 * Math.cos( Math.PI * t );
    }

Vladimír Ulman @xulman čvn 22 16:34
okay, I see now
jj, that's a variant of ease-in ease-out type of animation

tpietzsch @tpietzsch čvn 22 16:35
yes
```

**Comment by xulman** [comment]
the last commits fights @skalarproduktraum comment "When moving to a new node (I really love the animation there!), sometimes there's a roll around the Y axis introduced."

**Comment by xulman** [comment]
if you want the same branch w/o conflicts, consider https://github.com/xulman/sciview/tree/PR_UXchangesTakeTwo_rebasedOnNewMaster

this this branch rebased on the recent master, sadly I did "flat rebase" and the subtopics on this branch are not reflected in the commits listings...

**Comment by xulman** [comment]
> > When moving to a new node (I really love the animation there!), sometimes there's a roll around the Y axis introduced.
> 
> Plan B: replace content of `SciView.centerOnPosition()` with BDV's transforms interpolator:
> 

I'm not sure about the "Plan B" only because the scenery/sciview is implementing some camera movement restrictions (that became known as "no-roll cam moves")

**Comment by xulman** [comment]
HI,
I've rebased against the current master and tested (also against latest scenery and ui-behaviour-2.0.3-SNAPSHOT) -- also fixed ui-behaviour in its branch, I hope it'd be in upstream soon, we can perhaps wait for it here,

it compiles in IDE (hope also directly from maven...why not, right? :-),

the PR was originally touching upon some controls that I found already as .kt - so I've adapted the PR to improve the .kt in the end (along the way it actually re-creates relevant .java (somewhere deep in the branch) and then there is a commit to mv .java to .kt,
I also converted new controls of this PR to Kotlin as well

I can help with main sciview.java file, at least I can explain what, where, why


the `ControlsParameters` class remained, I'll get rid of it later by replacing it with properties as we agreed yday

**Pull request merged**
