### PR TITLE
Scenery 0.6.0

### PR DESCRIPTION
**Pull request by skalarproduktraum**
Changes to upgrade to scenery 0.6.0:

* fixes an issue where transfer functions are stored, and how LUTs are serialised
* adds a loading screen
* adds property editing for BoundingGrids, Volumes, and TextBoards

### CODE REVIEW

**Comment by skalarproduktraum** [comment]
@kephale: Ready to merge! :shipit:

**Comment by kephale** [comment]
On both vulkan and opengl, volume rendering seems off for all rendering modes. 

When running the game of life demo, it looks like only the surface is rendered for all rendering modes (except max project that doesn't render anything)

**Comment by skalarproduktraum** [comment]
Hey @kephale, 

I've fixed these issues in the latest snapshot. Would you mind having a look? If it looks good to you, I'd push 0.6.1 as a bugfix release 👍

**Comment by skalarproduktraum** [comment]
0.6.1 has been pushed, fixing the volume rendering issues, and again making LMIP the default rendering method.

**Pull request merged**
